title: QCM6490-KIT Development Portal
description: Yocto Project development portal for Qualcomm QCM6490 Development Kit
baseurl: /prj-QCM6490-KIT-PUB
url: https://yocto-machines.github.io

# Jekyll settings (GitHub Actions compatible)
markdown: kramdown
highlighter: rouge
theme: minima

# Minima theme configuration
minima:
  skin: dark
  social_links:
    github: yocto-machines

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Site variables
project:
  hub_repo: https://github.com/yocto-machines/yocto-gen-machines
  main_repo: https://github.com/yocto-machines/prj-QCM6490-KIT

# Custom CSS
sass:
  sass_dir: assets/css

# Include and exclude
include:
  - .htaccess
  - assets/css/custom.css
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.backup.*"
